/**
 * The `/nuxt` module, against a real directory tree and a stand-in Nuxt.
 *
 * `@nuxt/kit` is mocked: what is under test is which layers end up in each
 * theme's config and in what order, not Nuxt's template machinery. The module
 * running inside a real Nuxt 4 is what the demo is for.
 */
import type { Mock } from 'vitest'
import type { ModuleOptions } from '../src/nuxt'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { addTemplate } from '@nuxt/kit'
import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest'
import themedConfigsModule from '../src/nuxt'

vi.mock('@nuxt/kit', () => ({
  defineNuxtModule: vi.fn((module) => module),
  addTemplate: vi.fn(),
  // Every layer ships a UnoCSS config except `shared/empty`.
  findPath: vi.fn(async (_names: string[], { cwd }: { cwd: string }) =>
    cwd.endsWith('/shared/empty') ? null : `${cwd}/uno.config.ts`),
}))

interface Template {
  filename: string
  write: boolean
  getContents: () => Promise<string>
}

/**
 * `nuxt.options._layers` as Nuxt orders it: the project root first, then the
 * rest highest priority first - a layer the current command switched on, then
 * the active theme, then the shared layers.
 */
const LAYERS = ['', '.storybook', 'themes/beta', 'shared/three', 'shared/empty', 'shared/two', 'shared/one']

const OPTIONS: ModuleOptions = {
  themes: { alpha: 'themes/alpha', beta: 'themes/beta', missing: 'themes/missing' },
  shared: ['shared'],
}

describe('uno-themed-configs', () => {
  let rootDir: string

  beforeAll(() => {
    // Forward slashes, the way Nuxt hands `rootDir` over on every platform.
    rootDir = mkdtempSync(join(tmpdir(), 'uno-themed-configs-')).replaceAll('\\', '/')
    const file = (path: string): void => {
      mkdirSync(join(rootDir, path, '..'), { recursive: true })
      writeFileSync(join(rootDir, path), '')
    }

    file('themes/alpha/nuxt.config.ts')
    file('themes/alpha/uno.config.ts')
    file('themes/alpha/experiments/nuxt.config.ts')
    file('themes/alpha/experiments/uno.config.ts')
    // Not a layer root - no `nuxt.config` beside it - so `@unocss/nuxt` would
    // never load it, and neither should this.
    file('themes/alpha/components/stray/uno.config.ts')
    file('themes/beta/nuxt.config.ts')
    file('themes/beta/uno.config.ts')
  })

  afterAll(() => rmSync(rootDir, { recursive: true, force: true }))

  const setup = (options: ModuleOptions = OPTIONS): Template[] => {
    (addTemplate as Mock).mockClear()
    const _layers = LAYERS.map((path) => ({ config: { rootDir: path ? `${rootDir}/${path}` : rootDir } }))
    ;(themedConfigsModule as unknown as { setup: (o: ModuleOptions, n: unknown) => void })
      .setup(options, { options: { rootDir, _layers } })

    return (addTemplate as Mock).mock.calls.map(([template]) => template as Template)
  }

  const rawContentsFor = async (theme: string): Promise<string> => {
    const template = setup().find(({ filename }) => filename === `uno/config/${theme}.mjs`)!
    return template.getContents()
  }

  // The `@unocss/core` path is wherever this package's copy was installed;
  // a snapshot should not depend on the machine it ran on.
  const contentsFor = async (theme: string): Promise<string> =>
    (await rawContentsFor(theme))
      .replace(/from '[^']*@unocss\/core[^']*'/, 'from \'<@unocss/core>\'')
      .replaceAll(rootDir, '<root>')

  it('registers one template per theme, written to disk', () => {
    expect(setup().map(({ filename, write }) => [filename, write])).toEqual([
      ['uno/config/alpha.mjs', true],
      ['uno/config/beta.mjs', true],
      ['uno/config/missing.mjs', true],
    ])
  })

  it('registers nothing without themes', () => {
    expect(setup({ themes: {}, shared: ['shared'] })).toEqual([])
  })

  it('merges the shared layers in @unocss/nuxt order, then the theme\'s own, most specific last', async () => {
    // `.storybook` and the active theme (`beta`) are both enabled layers;
    // neither belongs in a config for `alpha`.
    expect(await contentsFor('alpha')).toMatchInlineSnapshot(`
      "// Generated by eslint-plugin-unocss-normalize-classes/nuxt. Do not edit.
      import { mergeConfigs } from '<@unocss/core>'
      import cfg0 from '<root>/shared/one/uno.config.ts'
      import cfg1 from '<root>/shared/two/uno.config.ts'
      import cfg2 from '<root>/shared/three/uno.config.ts'
      import cfg3 from '<root>/themes/alpha/uno.config.ts'
      import cfg4 from '<root>/themes/alpha/experiments/uno.config.ts'

      export default mergeConfigs([cfg0, cfg1, cfg2, cfg3, cfg4])
      "
    `)
  })

  it('imports @unocss/core by absolute path, so a strict install can still load the file', async () => {
    // The generated file sits in `<buildDir>/uno/config/`. Under strict pnpm,
    // nothing at the project root is reachable from there unless the project
    // lists `@unocss/core` itself - so the specifier cannot be left bare.
    const [, specifier] = /import \{ mergeConfigs \} from '([^']+)'/.exec(await rawContentsFor('alpha'))!
    expect(specifier).toMatch(/^(?:[A-Z]:)?\/.*\/@unocss\/core\/dist\/index\.mjs$/i)
    expect(specifier).not.toContain('\\')
  })

  it('reads the active theme from its own directory, like any other', async () => {
    const contents = await contentsFor('beta')
    expect(contents).toContain('import cfg3 from \'<root>/themes/beta/uno.config.ts\'')
    expect(contents).toContain('export default mergeConfigs([cfg0, cfg1, cfg2, cfg3])')
  })

  it('gives a theme with no directory only the shared layers', async () => {
    expect(await contentsFor('missing')).toContain('export default mergeConfigs([cfg0, cfg1, cfg2])')
  })

  it('declares the Nuxt versions it supports and the key its options live under', () => {
    const { meta } = themedConfigsModule as unknown as { meta: { configKey: string, compatibility: { nuxt: string } } }
    expect(meta.configKey).toBe('unoThemedConfigs')
    expect(meta.compatibility.nuxt).toBe('^3.17.0 || ^4.0.0')
  })
})
